<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function withCategory()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t, c FROM AppBundle:Todo t
                JOIN t.category c'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
